import React from 'react'
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import GoTop from "@/components/GoTop";

import benjamin_pavard from "@/assets/img/teams/benjamin_pavard.png";

import bg from "@/assets/img/horizontal.png";

export default function Detail() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <GoTop />

      <div className="relative w-full">
        <Image src={bg} alt="" className="w-full h-80" />
        <div className="absolute bottom-0 flex space-x-6 z-20">
          <div className="w-1/3 ">
            <Image src={benjamin_pavard} alt="" className="w-[900px]" />
          </div>
          <div className="flex flex-col space-y-0 w-2/3 justify-center">
            <div className="flex flex-col text-white w-24 leading-tight">
              <span className="text-4xl font-semibold">5</span>
              <div>
                <span className="text-4xl uppercase font-semibold">
                  Benjamin Pavard
                </span>
              </div>
            </div>
            <div>
              <span className="text-white uppercase text-xs font-bold">
                Defender
              </span>
            </div>
            <div className="py-4 flex space-x-2">
              <Link href={"/"} className="text-white">
                <span className="text-white">
                  <svg
                    height="22"
                    width="22"
                    viewBox="0 0 24 24"
                    preserveAspectRatio="xMidYMid meet"
                    role="img"
                    xmlns="http://www.w3.org/2000/svg"
                    className="eCHnXp"
                  >
                    <title>icon</title>
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M1.25 12C1.25 6.06294 6.06293 1.25 12 1.25C17.9371 1.25 22.75 6.06294 22.75 12C22.75 17.3664 18.8186 21.8129 13.6788 22.6195L12.8125 22.7554V14.1406H15.2488L15.4621 12.75H12.8125V10.1242C12.8125 9.61973 12.9348 9.02962 13.3442 8.55619C13.7712 8.06245 14.4081 7.8125 15.1921 7.8125H15.7031V6.75421C15.6883 6.75246 15.6733 6.75071 15.6581 6.74896C15.25 6.70183 14.7218 6.65625 14.2146 6.65625C13.2241 6.65625 12.4878 6.95361 12.0001 7.4418C11.5131 7.92924 11.1875 8.69342 11.1875 9.79688V12.75H8.64844V14.1406H11.1875V22.7554L10.3212 22.6195C5.18143 21.8129 1.25 17.3664 1.25 12ZM16.4531 6.10156L16.5793 5.36225L17.2031 5.46872V9.3125H15.1921C14.7339 9.3125 14.5561 9.44797 14.4788 9.53735C14.3839 9.64705 14.3125 9.83777 14.3125 10.1242V11.25H17.2097L16.5363 15.6406H14.3125V20.9586C18.3019 19.932 21.25 16.3097 21.25 12C21.25 6.89136 17.1086 2.75 12 2.75C6.89136 2.75 2.75 6.89136 2.75 12C2.75 16.3097 5.69805 19.932 9.6875 20.9586V15.6406H7.14844V11.25H9.6875V9.79688C9.6875 8.39408 10.1084 7.21295 10.9389 6.38164C11.7687 5.55108 12.921 5.15625 14.2146 5.15625C14.8016 5.15625 15.3926 5.20833 15.8302 5.25886C16.0506 5.28431 16.2357 5.30979 16.3665 5.32904C16.4319 5.33868 16.4839 5.34677 16.5201 5.35256L16.5624 5.35942L16.5741 5.36138L16.5775 5.36195L16.5793 5.36225C16.5794 5.36226 16.5793 5.36225 16.4531 6.10156Z"
                    ></path>
                  </svg>
                </span>
              </Link>
              <Link href={"/"} className="text-white">
                <span className="text-white">
                  <svg
                    height="22"
                    width="22"
                    viewBox="0 0 24 24"
                    preserveAspectRatio="xMidYMid meet"
                    role="img"
                    xmlns="http://www.w3.org/2000/svg"
                    className="base-icon__StyledIconSvg-sc-fzrbhv-0 eCHnXp"
                  >
                    <title>icon</title>
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M1.25 6C1.25 3.37665 3.37665 1.25 6 1.25H18C20.6234 1.25 22.75 3.37665 22.75 6V18C22.75 20.6234 20.6234 22.75 18 22.75H6C3.37665 22.75 1.25 20.6234 1.25 18V6ZM6 2.75C4.20507 2.75 2.75 4.20507 2.75 6V18C2.75 19.7949 4.20507 21.25 6 21.25H18C19.7949 21.25 21.25 19.7949 21.25 18V6C21.25 4.20507 19.7949 2.75 18 2.75H6ZM12 7.75C9.65279 7.75 7.75 9.65279 7.75 12C7.75 14.3472 9.65279 16.25 12 16.25C14.3472 16.25 16.25 14.3472 16.25 12C16.25 9.65279 14.3472 7.75 12 7.75ZM6.25 12C6.25 8.82436 8.82436 6.25 12 6.25C15.1756 6.25 17.75 8.82436 17.75 12C17.75 15.1756 15.1756 17.75 12 17.75C8.82436 17.75 6.25 15.1756 6.25 12ZM18.5 7C19.3284 7 20 6.32843 20 5.5C20 4.67157 19.3284 4 18.5 4C17.6716 4 17 4.67157 17 5.5C17 6.32843 17.6716 7 18.5 7Z"
                    ></path>
                  </svg>
                </span>
              </Link>
              <Link href={"/"} className="text-white">
                <span className="text-white">
                  <svg
                    height="22"
                    width="22"
                    viewBox="0 0 24 24"
                    preserveAspectRatio="xMidYMid meet"
                    role="img"
                    xmlns="http://www.w3.org/2000/svg"
                    className="base-icon__StyledIconSvg-sc-fzrbhv-0 eCHnXp"
                  >
                    <title>icon</title>
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M22.7489 1.55201L22.1977 3.53011C22.1232 3.79735 22.0368 4.05442 21.9484 4.29111L23.9214 3.28228L22.6493 5.48248C22.1499 6.34614 21.5278 7.12178 20.8083 7.76796L20.8136 8.0045V8.01291C20.8136 11.1356 19.7875 14.4977 17.8037 17.0948C15.8079 19.7078 12.8273 21.5589 8.9744 21.5589C6.59849 21.5589 4.39616 20.7533 2.5535 19.388L0.233276 17.6688L3.09684 18.0416C3.37247 18.0775 3.64994 18.097 3.92964 18.097C4.99575 18.097 6.01153 17.8228 6.92588 17.3245C5.57894 16.8311 4.32683 15.8235 3.46824 14.3374L2.60635 12.8456L4.28534 13.2312C4.27149 13.228 4.27187 13.228 4.29218 13.2292C4.30826 13.2302 4.33683 13.232 4.38074 13.2335C4.1457 13.0342 3.92215 12.8158 3.71473 12.5807C2.86794 11.6212 2.25001 10.3374 2.25001 8.85968V6.79288L3.41594 8.13826C3.17709 7.5032 3.04664 6.80724 3.04664 6.08253C3.04664 5.14199 3.26462 4.25296 3.65479 3.48298L4.21773 2.37202L4.93636 3.38924C6.564 5.69317 8.89061 7.25795 11.5086 7.67571C11.5068 7.61612 11.506 7.55634 11.506 7.4964C11.506 4.70396 13.49 2.25 16.1538 2.25C17.3581 2.25 18.439 2.76327 19.2491 3.5788C19.8865 3.38592 20.4916 3.0919 21.0525 2.70923L22.7489 1.55201ZM4.02077 10.2667C4.2124 10.7536 4.49593 11.199 4.83941 11.5882C5.49895 12.3356 6.3394 12.8293 7.06032 12.9967L9.75657 13.6227L7.1131 14.4435C7.09355 14.4496 7.07285 14.4561 7.0511 14.4629C6.75263 14.5564 6.25551 14.7122 5.79412 14.7122C5.75449 14.7122 5.69372 14.7136 5.61615 14.7157C6.55148 15.6771 7.71651 16.1527 8.78585 16.175L10.674 16.2145L9.2732 17.4812C8.23286 18.4219 6.98923 19.0977 5.62445 19.4074C6.67707 19.8302 7.80358 20.0589 8.9744 20.0589C12.2915 20.0589 14.8555 18.4836 16.6117 16.1843C18.3783 13.8715 19.3118 10.8393 19.3136 8.02121L19.2925 7.08316L19.5739 6.85157C19.8843 6.59608 20.1773 6.31008 20.4493 5.99757L19.5697 5.74107L20.0242 4.92084L20.0274 4.91497L20.0363 4.89854C19.7524 4.99943 19.4619 5.08422 19.1655 5.1519L18.7106 5.25575L18.4164 4.89361C17.8281 4.16945 17.0207 3.75 16.1538 3.75C14.5126 3.75 13.006 5.3239 13.006 7.4964C13.006 7.79976 13.0357 8.0938 13.092 8.37252L13.2849 9.32623L12.3135 9.26993C9.29268 9.09485 6.59228 7.6301 4.60167 5.38022C4.56559 5.607 4.54664 5.84172 4.54664 6.08253C4.54664 7.42753 5.14052 8.57802 5.98802 9.23144L7.84791 10.6654L5.50117 10.5748C5.10059 10.5594 4.54872 10.4506 4.02077 10.2667ZM20.6806 5.28379L20.4842 5.95714C20.4843 5.95698 20.4841 5.9573 20.4842 5.95714C20.5044 5.88723 20.5553 5.71344 20.6806 5.28379Z"
                    ></path>
                  </svg>
                </span>
              </Link>
            </div>
          </div>
        </div>
      </div>

      <div className="h-max flex flex-row space-x-6 px-4 py-0 md:py-4 justify-center2 items-center2 bg-[#f5f7f9]">
        <div className="w-1/2 flex flex-col space-y-4">
          <div className="flex flex-row justify-between mx-auto w-full md:w-12/12 space-x-6 items-center">
            <span className="text-2xl font-bold text-[#002f6c]">Personal</span>
          </div>
          <div className="flex space-x-2">
            <button className="flex rounded px-2 py-1 items-center bg-[#dc052d] hover:bg-blue-200">
              <span className=" font-semibold text-white text-sm">Details</span>
            </button>
            <button className="flex rounded px-2 py-1 items-center bg-blue-100 hover:bg-blue-200">
              <span className=" font-semibold text-[#002f6c] text-sm">Bio</span>
            </button>
            <button className="flex rounded px-2 py-1 items-center bg-blue-100 hover:bg-blue-200">
              <span className=" font-semibold text-[#002f6c] text-sm">
                Honours
              </span>
            </button>
          </div>

          <div className="flex justify-center border-y border-gray-300 ">
            <div className="flex flex-col w-full ">
              <div className="flex items-center border-b border-gray-300 py-3 px-3">
                <div className="w-5/12 text-sm font-semibold">
                  Contract Ends
                </div>
                <div className="w-7/12 text-sm font-mabry">30/06/2024</div>
              </div>
              <div className="flex items-center border-b border-gray-300 py-3 px-3">
                <div className="w-5/12 text-sm font-semibold">
                  Height
                </div>
                <div className="w-7/12 text-sm font-mabry">1.86 m</div>
              </div>
              <div className="flex items-center border-b border-gray-300 py-3 px-3">
                <div className="w-5/12 text-sm font-semibold">
                  Weight
                </div>
                <div className="w-7/12 text-sm font-mabry">81 kg</div>
              </div>
              <div className="flex items-center border-b border-gray-300 py-3 px-3">
                <div className="w-5/12 text-sm font-semibold">
                  Date of birth
                </div>
                <div className="w-7/12 text-sm font-mabry">28/03/1996</div>
              </div>
              <div className="flex items-center border-b border-gray-300 py-3 px-3">
                <div className="w-5/12 text-sm font-semibold">
                  Place of birth
                </div>
                <div className="w-7/12 text-sm font-mabry">Maubeuge, France</div>
              </div>
              <div className="flex items-center border-b border-gray-300 py-3 px-3">
                <div className="w-5/12 text-sm font-semibold">
                  Nationality
                </div>
                <div className="w-7/12 text-sm font-mabry">French</div>
              </div>
              <div className="flex items-center border-b border-gray-300 py-3 px-3">
                <div className="w-5/12 text-sm font-semibold">
                  Sign From
                </div>
                <div className="w-7/12 text-sm font-mabry">01/07/2019</div>
              </div>
              <div className="flex items-center border-b border-gray-300 py-3 px-3">
                <div className="w-5/12 text-sm font-semibold">
                  Former club
                </div>
                <div className="w-7/12 text-sm font-mabry">
                    <ul>
                        <li>Vfb Stuttgart (2016 - 2019)</li>
                        <li>OSC Lille (2014 - 2016)</li>
                        <li>US Jeumont</li>
                    </ul>
                </div>
              </div><div className="flex items-center border-b border-gray-300 py-3 px-3">
                <div className="w-5/12 text-sm font-semibold">
                  Prefered foot
                </div>
                <div className="w-7/12 text-sm font-mabry">Right</div>
              </div>
            </div>
          </div>
        </div>
        <div className="w-1/2 flex flex-col space-y-4">
            <div className="flex flex-row justify-between mx-auto w-full md:w-12/12 space-x-6 items-center">
                <span className="text-2xl font-bold text-[#002f6c]">Personal</span>
            </div>
            <div className="flex space-x-2 ">
                  <div className="flex flex-wrap md:flex-nowrap justify-end space-x-2">
                    <select
                      name="version"
                      className="input-select flex rounded px-2 py-1 items-center bg-blue-100 hover:bg-blue-200 font-semibold text-[#002f6c] text-sm"
                    >
                      <option value="all">All Season</option>
                      <option value="all">Season 2023/2024</option>
                      <option value="all">Season 2023/2024</option>
                      <option value="blog">Season 2023/2024</option>
                      <option value="boilerplate">Season 2023/2024</option>
                    </select>
                  </div>
                  <div className="flex space-x-2">
                    <div className="flex flex-wrap md:flex-nowrap items-center space-x-2">
                      <select
                        name="version"
                        className="input-select flex rounded px-2 py-1 items-center bg-blue-100 hover:bg-blue-200 font-semibold text-[#002f6c] text-sm"
                      >
                        <option value="all">All competitions</option>
                        <option value="all">DFB Cup</option>
                        <option value="blog">Champion League</option>
                        <option value="boilerplate">
                          International Champion Cup
                        </option>
                      </select>
                     
                    </div>
                  </div>
                </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
