import React from 'react'
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/components/Navbar";
import Footer from "@/components/FooterShop";
import ScrollTop from "@/components/ScrollTop";
import Suggest from "@/components/Suggest";

import product1 from "@/assets/img/product/product1.png";
import product2 from "@/assets/img/product/product2.png";
import product3 from "@/assets/img/product/product3.png";
import product4 from "@/assets/img/product/product4.png";
import product5 from "@/assets/img/product/product5.png";
import product6 from "@/assets/img/product/product6.png";
import product7 from "@/assets/img/product/product7.png";
import product8 from "@/assets/img/product/product8.png";
import product9 from "@/assets/img/product/product9.png";
import product10 from "@/assets/img/product/product10.png";
import product11 from "@/assets/img/product/product11.png";
import product12 from "@/assets/img/product/product12.png";
import Breadcrumb from '@/components/Breadcrumb';

export default function Wishlist() {

    const productData = [
        {
          title: "Manchester City Home Jersey 2023/24 with DE BRUYNE 17 printing",
          slug: "product-1",
          price: "91,00",
          img: product1,
        },
        {
          title: "Manchester City Home Jersey 2023/24 with DE BRUYNE 17 printing",
          slug: "product-1",
          price: "91,00",
          img: product2,
        },
        {
          title: "Manchester City Home Jersey 2023/24 with DE BRUYNE 17 printing",
          slug: "product-1",
          price: "91,00",
          img: product3,
        },
        {
          title: "Manchester City Home Jersey 2023/24 with DE BRUYNE 17 printing",
          slug: "product-1",
          price: "91,00",
          img: product4,
        },
        {
          title: "Manchester City Home Jersey 2023/24 with DE BRUYNE 17 printing",
          slug: "product-1",
          price: "91,00",
          img: product5,
        },
        {
          title: "Manchester City Home Jersey 2023/24 with DE BRUYNE 17 printing",
          slug: "product-1",
          price: "91,00",
          img: product6,
        },
        {
          title: "Manchester City Home Jersey 2023/24 with DE BRUYNE 17 printing",
          slug: "product-1",
          price: "91,00",
          img: product7,
        },
        {
          title: "Manchester City Home Jersey 2023/24 with DE BRUYNE 17 printing",
          slug: "product-1",
          price: "91,00",
          img: product8,
        },
        {
          title: "Manchester City Home Jersey 2023/24 with DE BRUYNE 17 printing",
          slug: "product-1",
          price: "91,00",
          img: product9,
        },{
          title: "Manchester City Home Jersey 2023/24 with DE BRUYNE 17 printing",
          slug: "product-1",
          price: "91,00",
          img: product10,
        },{
          title: "Manchester City Home Jersey 2023/24 with DE BRUYNE 17 printing",
          slug: "product-1",
          price: "91,00",
          img: product11,
        },{
          title: "Manchester City Home Jersey 2023/24 with DE BRUYNE 17 printing",
          slug: "product-1",
          price: "91,00",
          img: product12,
        },
      ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ScrollTop />
      <Breadcrumb />


      <div className="h-max flex flex-col space-y-3 px-0 md:px-6 py-4 md:py-4 justify-center2 items-center2 bg-[#f5f7f9]">
        <div className="mx-auto w-full md:w-12/12 lg:w-1/2">
          <Link
            href={"/"}
            className="flex space-x-1 items-center hover:opacity-80"
          >
            <span className="text-lg md:text-2xl font-bold text-[#002f6c] uppercase">
              Wishlist
            </span>
          </Link>
         
        </div>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-2 mx-auto w-full md:w-12/12 lg:w-1/2">
        {productData.map((data, index) => {
            return (
              <Link
                href={`/shop/${data.slug}`}
                className="transform overflow-hidden m-3 bg-white border shadow duration-200 hover:scale-105 cursor-pointer"
                key={index}
              >
                <div className="bg-[#f3f6f9] p-2">
                <Image
                  width={500}
                  height={500}
                  src={data.img}
                  alt={data.title}
                />
                </div>
                <div className="p-2 text-black/[0.9]">
                  <h2 className="text-base font-medium leading-tight">{data.title}</h2>
                  <div className="flex items-center text-black/[0.5]">
                    <p className="mr-2 text-lg text-gray-950 font-semibold">
                      &#8377;{data.price}
                    </p>

                    {data.price && (
                      <>
                        <p className="text-base  font-medium line-through">
                          &#8377;{data.price}
                        </p>
                      </>
                    )}
                  </div>
                </div>
                <div className='flex w-full items-center'>
                <button className="flex w-full rounded2 py-2 bg-transparent items-center justify-center text-sm text-center border border-[#32e6e2] text-[#32e6e2] font-semibold cursor-pointer hover:bg-[#32e6e2] hover:text-slate-700 hover:border-slate-800">
                  Add to cart
                </button>
                <button className="flex w-full rounded2 py-2 bg-[#32e6e2] items-center justify-center text-sm text-center border border-[#32e6e2] text-[#181a1c] font-semibold cursor-pointer hover:bg-slate-700 hover:text-white">
                  Remove
                </button>
                </div>
              </Link>
            );
          })}
        </div>
        </div>

      <Footer />
    </>
  )
}
