import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SubscribeForm from "@/components/SubscribeForm";
import GoTop from "@/components/GoTop";

import history from "@/assets/img/history/history.png";
import history1 from "@/assets/img/history/history1.jpg";
import history2 from "@/assets/img/history/history2.jpg";
import history3 from "@/assets/img/history/history3.jpg";


import Season from "@/components/Season";

export default function History() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <div
        className="relative w-full flex flex-col justify-center md:h-[480px] mx-auto h-[193px] xs:items-center xs:justify-center md:items-start md:justify-center text-white"
      >
        <div className="absolute w-full h-full">
          <div className="w-full h-full">
            <div className="hidden2 md:block md:w-full md:h-full relative animate-[fadeIn_0.3s_ease-out]">
              <Image src={history} alt="" className="object-cover h-full" />
            </div>
          </div>
        </div>
        <div className="z-10 h-full flex flex-col justify-center bg-[#0066b2]/70 items-center text-center  xs:my-[12px] md:my-[48px] px-[12px] md:px-[30px] md:w-[380px] relative xs:items-center xs:text-center xs:justify-center md:items-start md:text-left md:justify-center">
          <h3 className="font-bold mb-[12px] text-2xl md:text-h5 md:mb-[20px]">
          HIS­TORY
          </h3>
          <div className=" leading-tight text-md md:text-lg mb-[8px] md:mb-[24px]">
            <div>
              <div>
                <p className="leading-tight">
                Bayer 04 stand for attractive top quality football – in Germany and beyond. The club was promoted to the Bundesliga in 1979 and seven years later saw the Werkself qualify for Europe for the first time. The Werkself have now been on the European stage for decades and in the top-flight for more than 40 years. Around 300 people currently work for Bayer 04 Leverkusen Fußball Gmbh.
                </p>
              </div>
            </div>
          </div>
          <div className="flex gap-3"></div>
        </div>
      </div>

      <Season />

      <div className="h-max flex flex-col space-y-3 px-0 md:px-6 py-4 md:py-4 justify-center2 items-center2 bg-[#f5f7f9]">
        <div className="mx-auto w-12/12 md:w-12/12 lg:w-1/2">
          <div className="flex flex-row justify-between mx-auto md:mx-0 w-11/12 md:w-12/12 lg:w-1/2 space-x-6 items-center">
            <div className="flex space-x-1 items-center hover:opacity-80">
              <span className="text-lg md:text-2xl font-bold text-[#002f6c] uppercase">
                Related News
              </span>
            </div>
          </div>
          <div className="flex flex-row flex-wrap  mx-auto w-full md:w-12/12 ">
            <div className="px-3 py-3 w-1/2 md:w-1/3 lg:w-1/3">
              <div className=" bg-white group flex flex-col overflow-hidden hover:scale-105 shadow ">
                <Link href="/news/one" className="relative">
                  <Image
                    src={history1}
                    alt=""
                    className="w-full object-cover"
                  />{" "}
                  <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                </Link>{" "}
                <div className="px-3 py-2 pb-4 flex flex-col space-y-1 leading-tight">
                  <div className="font-semibold text-xs md:text-xs uppercase text-red-500">
                    Membership
                  </div>
                  <Link href="/news/one">
                    <span className="font-semibold text-base md:text-md text-[#002f6c] leading-tight">
                      Become part of the FC Bayern family!
                    </span>
                  </Link>
                </div>
              </div>
            </div>

            <div className="px-3 py-3 w-1/2 md:w-1/3 lg:w-1/3">
              <div className=" bg-white group flex flex-col overflow-hidden hover:scale-105 shadow ">
                <Link href="/news/one" className="relative">
                  <Image
                    src={history2}
                    alt=""
                    className="w-full object-cover"
                  />{" "}
                  <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                </Link>{" "}
                <div className="px-3 py-2 pb-4 flex flex-col space-y-1 leading-tight">
                  <div className="font-semibold text-xs md:text-xs uppercase text-red-500">
                    Membership
                  </div>
                  <Link href="/news/one">
                    <span className="font-semibold text-base md:text-md text-[#002f6c] leading-tight">
                      Become part of the FC Bayern family!
                    </span>
                  </Link>
                </div>
              </div>
            </div>

            <div className="px-3 py-3 w-1/2 md:w-1/3 lg:w-1/3">
              <div className=" bg-white group flex flex-col overflow-hidden hover:scale-105 shadow ">
                <Link href="/news/one" className="relative">
                  <Image
                    src={history3}
                    alt=""
                    className="w-full object-cover"
                  />{" "}
                  <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                </Link>{" "}
                <div className="px-3 py-2 pb-4 flex flex-col space-y-1 leading-tight">
                  <div className="font-semibold text-xs md:text-xs uppercase text-red-500">
                    Membership
                  </div>
                  <Link href="/news/one">
                    <span className="font-semibold text-base md:text-md text-[#002f6c] leading-tight">
                      Become part of the FC Bayern family!
                    </span>
                  </Link>
                </div>
              </div>
            </div>

            <div className="px-3 py-3 w-1/2 md:w-1/3 lg:w-1/3">
              <div className=" bg-white group flex flex-col overflow-hidden hover:scale-105 shadow ">
                <Link href="/news/one" className="relative">
                  <Image
                    src={history1}
                    alt=""
                    className="w-full object-cover"
                  />{" "}
                  <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                </Link>{" "}
                <div className="px-3 py-2 pb-4 flex flex-col space-y-1 leading-tight">
                  <div className="font-semibold text-xs md:text-xs uppercase text-red-500">
                    Membership
                  </div>
                  <Link href="/news/one">
                    <span className="font-semibold text-base md:text-md text-[#002f6c] leading-tight">
                      Become part of the FC Bayern family!
                    </span>
                  </Link>
                </div>
              </div>
            </div>

            <div className="px-3 py-3 w-1/2 md:w-1/3 lg:w-1/3">
              <div className=" bg-white group flex flex-col overflow-hidden hover:scale-105 shadow ">
                <Link href="/news/one" className="relative">
                  <Image
                    src={history2}
                    alt=""
                    className="w-full object-cover"
                  />{" "}
                  <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                </Link>{" "}
                <div className="px-3 py-2 pb-4 flex flex-col space-y-1 leading-tight">
                  <div className="font-semibold text-xs md:text-xs uppercase text-red-500">
                    Membership
                  </div>
                  <Link href="/news/one">
                    <span className="font-semibold text-base md:text-md text-[#002f6c] leading-tight">
                      Become part of the FC Bayern family!
                    </span>
                  </Link>
                </div>
              </div>
            </div>

            <div className="px-3 py-3 w-1/2 md:w-1/3 lg:w-1/3">
              <div className=" bg-white group flex flex-col overflow-hidden hover:scale-105 shadow ">
                <Link href="/news/one" className="relative">
                  <Image
                    src={history3}
                    alt=""
                    className="w-full object-cover"
                  />{" "}
                  <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                </Link>{" "}
                <div className="px-3 py-2 pb-4 flex flex-col space-y-1 leading-tight">
                  <div className="font-semibold text-xs md:text-xs uppercase text-red-500">
                    Membership
                  </div>
                  <Link href="/news/one">
                    <span className="font-semibold text-base md:text-md text-[#002f6c] leading-tight">
                      Become part of the FC Bayern family!
                    </span>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <SubscribeForm />

      <Footer />
    </>
  );
}
