import React, { useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SubscribeForm from "@/components/SubscribeForm";
import NewsRelated from "@/components/NewsRelated";
import GoTop from "@/components/GoTop";

import hero from "@/assets/img/club/arenaumbau_08_duc_030818.png";
import HomeClub from "@/components/HomeClub";

export default function Club() {
  return (
    <>
    <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <GoTop />

        <div className="h-max  flex flex-row space-x-6 md:px-6 py-0 md:py-4 justify-center2 items-center2 bg-[#f5f7f9]">
      <div className="mx-auto w-full lg:w-1/2">
        <Image src={hero} alt="" />
      </div>
        </div>


        <HomeClub />
        <SubscribeForm />
        <NewsRelated />

        <Footer />
    </>
  )
}
