import Banner from '@/components/Banner'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import HomeAwards from '@/components/HomeAwards'
import HomeMatch from '@/components/HomeMatch'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-[#f5f7f9]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HomeMatch />
      <Banner />
      <HomeAwards />
      <Footer />
    </div>
  )
}
