import React from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import GoTop from "@/components/GoTop";

import NewsRelated from "@/components/NewsRelated";

import bg from "@/assets/img/fans/fans_bg.png";
import fans1 from "@/assets/img/fans/fans1.png";
import fans2 from "@/assets/img/fans/fans2.png";
import digi1 from "@/assets/img/fans/digital1.png";
import digi2 from "@/assets/img/fans/digital2.jpg";
import digi3 from "@/assets/img/fans/digital3.jpg";

export default function Fans() {
  const dataFans = [
    {
      image: fans1,
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <GoTop />

      <div className="h-max  flex flex-row space-x-6 md:px-6 py-0 md:py-4 justify-center2 items-center2 bg-[#f5f7f9]">
        <div className="mx-auto w-full lg:w-1/2">
          <Image src={bg} alt="" />
        </div>
      </div>

      <NewsRelated />
      <Footer />
    </>
  );
}
