import React from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import GoTop from "@/components/GoTop";

import media1 from "@/assets/img/media/media1.png";
import media2 from "@/assets/img/media/media2.png";
import media3 from "@/assets/img/media/media3.png";
import media4 from "@/assets/img/media/media4.png";
import media5 from "@/assets/img/media/media5.png";
import media6 from "@/assets/img/media/media6.png";
import media7 from "@/assets/img/media/media7.png";
import media8 from "@/assets/img/media/media8.png";
import media9 from "@/assets/img/media/media9.png";
import media10 from "@/assets/img/media/media10.png";
import media11 from "@/assets/img/media/media11.png";
import SlideMedia from "@/components/SlideMedia";
import Highlight from "@/components/Highlight";

export default function Media() {
  const mediaData = [
    {
      title:
        "Team talks, rituals, favourite food: Dressing room insights from Bayern players",
      img: media1,
    },
    {
      title:
        "Team talks, rituals, favourite food: Dressing room insights from Bayern players",
      img: media2,
    },
    {
      title:
        "Team talks, rituals, favourite food: Dressing room insights from Bayern players",
      img: media3,
    },
    {
      title:
        "Team talks, rituals, favourite food: Dressing room insights from Bayern players",
      img: media4,
    },
    {
      title: "Kingsley Coman completes running session at Säbener Straße",
      img: media5,
    },
    {
      title: "Tuchel’s press conference before Mainz home game",
      img: media6,
    },
    {
      title: "Reaction to Mathys Tel's contract extension",
      img: media9,
    },
    {
      title:
        "Team talks, rituals, favourite food: Dressing room insights from Bayern players",
      img: media8,
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <GoTop />

      <div className="bg-[#00091a] w-full h-full">
        <SlideMedia />

        <div className="h-max mx-auto w-full lg:w-1/2 flex flex-col space-y-4 md:px-4 py-5 md:py-4 lg:px-0 justify-center2 items-center2 bg-transparent">
          <div className="flex flex-row justify-between mx-auto w-full md:w-12/12 space-x-6 items-center">
            <div className="flex space-x-1 items-center">
              <span className="text-lg md:text-2xl font-bold text-white">
                Latest Video
              </span>
            </div>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-2 lg:grid-cols-2 mx-auto w-full md:w-12/12 ">
            {mediaData.map((data, index) => (
              <div className="px-3 py-3 w-full" key={index}>
                <div className=" bg-white group flex flex-col overflow-hidden rounded border border-gray-700 hover:scale-105 shadow ">
                  <Link href="/news/one" className="relative">
                    <div className="absolute z-10 bottom-0 h-40 w-full bg-gradient-to-b from-transparent to-[#0a1016]"></div>
                    <Image src={data.img} alt="" className="w-full" />{" "}
                    <div className="absolute bottom-0  group-hover:opacity-75 z-20 ">
                      <div className="px-3 py-2 pb-4 flex flex-col space-y-1 leading-tight">
                        <div className="w-10 h-10 font-semibold text-xs md:text-xs uppercase text-red-500">
                          <svg
                            viewBox="0 0 24 24"
                            preserveAspectRatio="xMidYMid meet"
                            role="img"
                            xmlns="http://www.w3.org/2000/svg"
                            className="base-icon__StyledIconSvg-sc-fzrbhv-0 eCHnXp"
                          >
                            <title>icon</title>
                            <path
                              fillRule="evenodd"
                              clipRule="evenodd"
                              d="M6 4.5H18C19.933 4.5 21.5 6.067 21.5 8V16C21.5 17.933 19.933 19.5 18 19.5H6C4.067 19.5 2.5 17.933 2.5 16V8C2.5 6.067 4.067 4.5 6 4.5ZM1 8C1 5.23858 3.23858 3 6 3H18C20.7614 3 23 5.23858 23 8V16C23 18.7614 20.7614 21 18 21H6C3.23858 21 1 18.7614 1 16V8ZM15 12L10 9V15L15 12Z"
                            ></path>
                          </svg>
                        </div>

                        <Link href="/news/one">
                          <span className="font-bold text-base md:text-md text-white leading-tight">
                            {data.title}
                          </span>
                        </Link>
                      </div>
                    </div>
                  </Link>{" "}
                </div>
              </div>
            ))}
          </div>
        </div>

        <Highlight />
      </div>

      <Footer />
    </>
  );
}
